config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  authenticate :user do
  get '/dash', to: 'dash#index', as: :dash_index

  get '/dash/create-transaction', to: 'dash#make_transaction', as: :dash_transaction

  get '/dash/gift', to: 'dash#gift_transaction', as: :dash_send_transaction

  post '/dash/transaction', to: 'dash#create_transaction', as: :create_transaction

  post 'dash/gift_transaction', to: 'dash#user_send_transaction', as: :user_send_transaction

  post '/shop/buy', to: 'shop#buy', as: :buy_item

  get '/shop', to: 'shop#index', as: :shop_index

  get '/shop/:name', to: 'shop#category', as: :category_show

  get '/gacha', to: 'gacha#index', as: :gacha_index

  post '/gacha', to: 'gacha#gacha', as: :roll_gacha

  get '/zashuu', to: 'zashuu#index', as: :zashuu_page

  get '/coupon', to: 'coupon#index', as: :coupon_index

  get '/coupon/redeem', to: 'coupon#redeem', as: :coupon_redemption

  patch '/coupon/redemption', to: 'coupon#redeem_coupon', as: :redeem_coupon

    resources :wishlist, only: [:index, :create, :destroy]

  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @categories = ShopCategory.all
  end

  def category
    @category = ShopCategory.find_by name: params[:name]
    #@items = ShopItem.find_by shop_category_id:@category.id #(shop_catergory_id:@category.id)
    @items = ShopItem.where(shop_category_id: @category.id)
    render 'shop/category'
  end

  def buy
    item = ShopItem.find_by id: params[:item_id]
    if current_user.hamsterbux < item.price
      return
    end
    new_transaction = Transaction.new({amount: item.price, description: "purchased #{item.name}", user: current_user, process_time: Time.now.strftime('%d/%m/%Y %HL%M')})
    current_user.hamsterbux -= new_transaction.amount
    unless new_transaction.save
      return
    end
    current_user.save

    value = (0...8).map { (65 + rand(26)).chr }.join
    new_coupon = Coupon.new({used: false, user: current_user, shop_item: item, code: value})
    new_coupon.save

    redirect_to :dash_index
  end


end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/category.html.erb
<div class="title"><h1><%= @category.name %></h1></div>
<div>
  <div class="container">
    <% @items.each do |item| %>
        <div class="item-container">
          <div style="margin-top:10px" ;><b><%= item.name %></b></div>
          <div style="width: 100px; height: 100px; margin: 10px;"><%= image_tag item.picture, style: 'max-height: 100%; max-width: 100%' %></div>
          <div style="margin-bottom: 10px; display: flex;  ">
            price: <%= item.price %><%= image_tag 'seed.png', size: '25', style: "margin-left: 10px;" %></div>
          <%= link_to 'buy', buy_item_path({item_id: item.id}), method: :post, class: 'btn btn-warning btn-lg', style: 'justify-content: center;' %>
          <button type="button" class="btn btn-danger" style="margin-bottom:10px;">Add to wish list</button>
        </div>
    <% end %>

  </div>
  <div style="display: flex; align-items: center; justify-content: center;">
    <div>
  <%= link_to 'back', shop_index_path, class: 'welcome-button btn btn-primary btn-lg', style: 'justify-content: center;' %>
    </div>
  </div>
</div>

app/views/shop/index.html.erb
<div class = "title"><h1>Welcome to the Hamster Shop!~</h1></div>

<div class="container">

  <% @categories.each do |category|%>
      <%= link_to category_show_path category.name do %>
        <div class="category-container" ><div><b><%= category.name %></b></div></div>
      <% end %>
  <% end %>
</div>