config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  authenticate :user do
  get '/dash', to: 'dash#index', as: :dash_index

  get '/dash/create-transaction', to: 'dash#make_transaction', as: :dash_transaction

  get '/dash/gift', to: 'dash#gift_transaction', as: :dash_send_transaction

  post '/dash/transaction', to: 'dash#create_transaction', as: :create_transaction

  post 'dash/gift_transaction', to: 'dash#user_send_transaction', as: :user_send_transaction

  post '/shop/buy', to: 'shop#buy', as: :buy_item

  get '/shop', to: 'shop#index', as: :shop_index

  get '/shop/:name', to: 'shop#category', as: :category_show

  get '/gacha', to: 'gacha#index', as: :gacha_index

  post '/gacha', to: 'gacha#gacha', as: :roll_gacha

  get '/zashuu', to: 'zashuu#index', as: :zashuu_page

  get '/coupon', to: 'coupon#index', as: :coupon_index

  get '/coupon/redeem', to: 'coupon#redeem', as: :coupon_redemption

  patch '/coupon/redemption', to: 'coupon#redeem_coupon', as: :redeem_coupon

    resources :wishlist, only: [:index, :create, :destroy]

  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dash_controller.rb
class DashController < ApplicationController
  before_action :filter_admin, only: [:make_transaction, :create_transaction]
  def index
    Time.zone="America/Los_Angeles"
    @transaction = Transaction.all
  end
  def transaction
    @transac = Transaction.find_by user: params[:user]
  end
  def make_transaction
    @transaction = Transaction.new
  end
  def create_transaction
    user = User.find_by( name: params[:transaction][:username])
    new_transaction = Transaction.new(transaction_params(user.id))
    user.hamsterbux += new_transaction.amount
    new_transaction.save
    user.save
    redirect_to :dash_index
  end

  def gift_transaction
    @transaction = Transaction.new
  end
  def user_send_transaction
    gifter = current_user
    receiver = User.find_by( name: params[:transaction][:username])
    unless receiver
      flash[:notice] = "Receiver doesn't exist."
      redirect_to :dash_send_transaction
      return
    end
    new_transaction_gifter = Transaction.new(transaction_params(gifter.id))
    gifter.hamsterbux-= new_transaction_gifter.amount
    new_transaction_gifter.save
    gifter.save

    new_transaction_receiver = Transaction.new(transaction_params(receiver.id))
    receiver.hamsterbux+= new_transaction_receiver.amount
    new_transaction_receiver.save
    receiver.save

    redirect_to :dash_index
  end

  private
  def transaction_params(user_id)
    tp = params.require(:transaction).permit(:amount,:description)
    tp[:user_id] = user_id
    tp
  end

  def filter_admin
    unless current_user.admin
      redirect_to :dash_index
    end
  end
end

app/helpers/dash_helper.rb
module DashHelper
end

app/views/dash/gift_transaction.html.erb
<div class = "main-stuff">
  <h2>Gift Some Hamsterbux</h2>
</div>

<div class = "transaction-form">

  <%= form_for(@transaction, url: user_send_transaction_path) do |f| %>
      <%- flash.each do |name, msg| -%>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
      <%- end -%>

      <div>

        <div class="form-group">
          <%= f.label :username, 'Username' %><br/>
          <%= f.text_field :username, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :amount, "Gift Hamsterbux" %><br/>
          <%= f.text_field :amount, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Transaction Description" %><br/>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit 'submit!', class: 'register-button btn btn-primary btn-lg' %>
        </div>
      </div>


  <% end %>
</div>

app/views/dash/index.html.erb
<div class="greetings">
  <h1>Greetings!!!</h1>
  <h2>こんにちは !</h2>
  <h2>你好 !</h2>
  <div><h2>Balance: <%= current_user.hamsterbux %> <%= image_tag 'seed.png', size: '25' %></h2></div>
  <h2>Recent Transactions: </h2>
  <h4>
    <div class="teeburu">
      <table class="table">
        <thead>
        <tr>
          <th>Date</th>
          <th>Amount</th>
          <th>Description</th>
        </tr>
        </thead>

        <tbody>
        <% @transaction.each do |transaction| %>
            <tr style="text-align:left;">
              <td><%= transaction.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
              <td><%= transaction.amount %></td>
              <td><%= transaction.description %></td>
            </tr>
        <% end %>
        </tbody>

      </table>
    </div>
  </h4>
</div>

<div class="button-container">
  <%= link_to 'Shop', shop_index_path, class: 'shop-button btn btn-primary btn-lg' %>
  <button type="button" class="btn btn-secondary btn-lg">Earn Hamsterbux</button>
  <%= link_to 'Gift', dash_send_transaction_path, class: 'gift-button btn btn-primary btn-lg' %>
  <% if current_user.admin%>
    <%= link_to 'Give Hamsterbux', dash_transaction_path, class: 'shop-button btn btn-secondary btn-lg' %>
  <% end %>
</div>

app/views/dash/make_transaction.html.erb
<div class = "main-stuff">
  <h2>Make A Transaction</h2>
</div>

<div class = "transaction-form">

  <%= form_for(@transaction, url: create_transaction_path) do |f| %>
      <%- flash.each do |name, msg| -%>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
      <%- end -%>

      <div>

        <div class="form-group">
          <%= f.label :username, 'Username' %><br/>
          <%= f.text_field :username, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :amount, "Add Hamsterbux" %><br/>
          <%= f.text_field :amount, autofocus: true, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Transaction Description" %><br/>
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit 'submit!', class: 'register-button btn btn-primary btn-lg' %>
        </div>
      </div>


  <% end %>
</div>