config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  authenticate :user do
  get '/dash', to: 'dash#index', as: :dash_index

  get '/dash/create-transaction', to: 'dash#make_transaction', as: :dash_transaction

  get '/dash/gift', to: 'dash#gift_transaction', as: :dash_send_transaction

  post '/dash/transaction', to: 'dash#create_transaction', as: :create_transaction

  post 'dash/gift_transaction', to: 'dash#user_send_transaction', as: :user_send_transaction

  post '/shop/buy', to: 'shop#buy', as: :buy_item

  get '/shop', to: 'shop#index', as: :shop_index

  get '/shop/:name', to: 'shop#category', as: :category_show

  get '/gacha', to: 'gacha#index', as: :gacha_index

  post '/gacha', to: 'gacha#gacha', as: :roll_gacha

  get '/zashuu', to: 'zashuu#index', as: :zashuu_page

  get '/coupon', to: 'coupon#index', as: :coupon_index

  get '/coupon/redeem', to: 'coupon#redeem', as: :coupon_redemption

  patch '/coupon/redemption', to: 'coupon#redeem_coupon', as: :redeem_coupon

    resources :wishlist, only: [:index, :create, :destroy]

  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/coupon.rb
# == Schema Information
#
# Table name: coupons
#
#  id           :integer          not null, primary key
#  used         :boolean
#  user_id      :integer
#  shop_item_id :integer
#  code         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_coupons_on_shop_item_id  (shop_item_id)
#  index_coupons_on_user_id       (user_id)
#

class Coupon < ApplicationRecord
  belongs_to :shop_item
  belongs_to :user
end

app/controllers/coupon_controller.rb
class CouponController < ApplicationController
def index
  @coupons = Coupon.where(user: current_user)
end

def redeem
  @redeem_coupon = Coupon.new
end

def redeem_coupon
  @redeem_coupon = Coupon.find_by(code: params[:coupon][:code])
  unless @redeem_coupon
    flash[:error] =  "Cannot find coupon."
    redirect_to :coupon_redemption
    return
  end
  if @redeem_coupon.used = true
    flash[:error] = "Coupon already used."
    redirect_to :coupon_redemption
    return
  end
  @redeem_coupon.used = true
  @redeem_coupon.save
  redirect_to :coupon_index
end
end

app/helpers/coupon_helper.rb
module CouponHelper
end

app/views/coupon/index.html.erb
<div class="main-stuff">
  <h2>coupons</h2>
</div>

<% @coupons.each do |coupon| %>
    <div class="coupon">
      <div class="coupon-container">
        <div class = "coupon-name"><b><%= coupon.shop_item.name %></b></div>
        <div class = "coupon-code"><%= coupon.code %></div>
        <div class = "coupon-pic"><%= image_tag coupon.shop_item.picture, style: 'max-height: 50px; max-width: 50px' %></div>
      </div>
    </div>
<% end %>

app/views/coupon/redeem.html.erb
<div class = "main-stuff">
  <h2>Redeem A Coupon</h2>
</div>

<div class = "redemption-form">

  <%= form_for(@redeem_coupon, method: :patch, url: redeem_coupon_path) do |f| %>
      <%- flash.each do |name, msg| -%>
          <div class="alert alert-danger">
            <%= msg %>
          </div>
      <%- end -%>

      <div>
        <div class="form-group">
          <%= f.label :code, "Enter coupon code" %><br/>
          <%= f.text_field :code, autofocus: true, class: 'form-control' %>
        </div>

        <div class="actions">
          <%= f.submit 'submit!', class: 'register-button btn btn-primary btn-lg' %>
        </div>
      </div>


  <% end %>
</div>