config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  authenticate :user do
  get '/dash', to: 'dash#index', as: :dash_index

  get '/dash/create-transaction', to: 'dash#make_transaction', as: :dash_transaction

  get '/dash/gift', to: 'dash#gift_transaction', as: :dash_send_transaction

  post '/dash/transaction', to: 'dash#create_transaction', as: :create_transaction

  post 'dash/gift_transaction', to: 'dash#user_send_transaction', as: :user_send_transaction

  post '/shop/buy', to: 'shop#buy', as: :buy_item

  get '/shop', to: 'shop#index', as: :shop_index

  get '/shop/:name', to: 'shop#category', as: :category_show

  get '/gacha', to: 'gacha#index', as: :gacha_index

  post '/gacha', to: 'gacha#gacha', as: :roll_gacha

  get '/zashuu', to: 'zashuu#index', as: :zashuu_page

  get '/coupon', to: 'coupon#index', as: :coupon_index

  get '/coupon/redeem', to: 'coupon#redeem', as: :coupon_redemption

  patch '/coupon/redemption', to: 'coupon#redeem_coupon', as: :redeem_coupon

    resources :wishlist, only: [:index, :create, :destroy]

  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wishlist.rb
# == Schema Information
#
# Table name: wishlists
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  shop_item_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_wishlists_on_shop_item_id  (shop_item_id)
#  index_wishlists_on_user_id       (user_id)
#

class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :shop_item
end

app/controllers/wishlist_controller.rb
class WishlistController < ApplicationController
  def index
    @wishtems = Wishlist.where(user: current_user)
  end

  def create
    new_wishlist_item = Wishlist.new({user: current_user, shop_item_id: params[:item_id]})
    new_wishlist_item.save
  end

  def destroy
    item = Wishlist.find params[:id]
    item.destroy
    redirect_to :wishlist_index
  end
end

app/helpers/wishlist_helper.rb
module WishlistHelper
end

app/views/wishlist/index.html.erb
<div class="main-title">
  <h2>wishlist</h2>
</div>

<% @wishtems.each do |wishtem| %>
    <div class="wishtem">
      <div class="wishtem-container">
        <div class = "wishtem-name"><b><%= wishtem.shop_item.name %></b></div>
        <div class = "wishtem-pic"><%= image_tag wishtem.shop_item.picture, style: 'max-height: 50px; max-width: 50px' %></div>
        <div>
          <%= link_to 'delete', wishlist_path(wishtem), method: :delete, class: 'welcome-button btn btn-secondary btn-lg', style: 'justify-content: center;' %>
        </div>
      </div>
    </div>
<% end %>